apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-container
        image: onyekaembedded/backend-app:v2
        ports:
        - containerPort: 5050
        env:
        - name: MONGODB_URL
          value: "mongodb://mongo-service:27017/Employees"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP
